# The MIT License (MIT)
# Copyright © 2023 Yuma Rao
# Copyright © 2025 TalkHead AI

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the “Software”), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of
# the Software.

# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
import numpy as np
from typing import List, Tuple, Dict, Optional
import bittensor as bt
from talkhead.constants import TALKHEAD_SERVER_HOST, SCORING_SERVER_ENDPOINT, TESTNET_SCORING_SERVER_ENDPOINT
import requests
from talkhead.protocol import TalkHeadSynapse

def reward(self, step: int, synapse: TalkHeadSynapse, video_url: str) -> Tuple[float, Dict, Optional[float]]:
    """
    Reward the miner response to the challenge request. This method returns a reward
    value for the miner, which is used to update the miner's score.

    Args:
    - step (int): The current validator step.
    - synapse (TalkHeadSynapse): The synapse object containing the challenge request and miner response.
    - video_url (str): The URL of the video generated by the miner.
    Returns:
    - float: The reward value for the miner.
    """
    if not video_url:
        bt.logging.error("Received response without video; assigning zero reward.")
        return 0.0, {"reason": "Received response without video"}, None

    payload = {
        "text": synapse.text,
        "video_url": video_url,
        "image_base64": synapse.image_base64,
        "language": "en-US",
        "voice_profile": synapse.voice_profile,
    }

    url = SCORING_SERVER_ENDPOINT if self.subtensor.network != "test" else TESTNET_SCORING_SERVER_ENDPOINT
    headers = self.build_signed_headers(f"/score")
    try:
        scoring_response = requests.post(
            url,
            json=payload,
            headers=headers,
            timeout=60,
        )
        scoring_response.raise_for_status()
        result = scoring_response.json()
    except requests.RequestException as err:
        bt.logging.error(f"Failed to score miner response: {err}")
        return 0.0, {"reason": "Failed to score miner response"}, None
    except ValueError:
        bt.logging.error("Scoring server returned non-JSON response.")
        return 0.0, {"reason": "Scoring server returned non-JSON response"}, None

    composite_score = result.get("composite")
    duration_sec = result.get("duration_sec")
    bt.logging.debug(f"Scoring server response => composite_score: {composite_score} | reason: {result.get('reason', 'No reason provided')}")
    if composite_score is None:
        bt.logging.error(f"Scoring server response missing 'composite': {result}")
        return 0.0, {"reason": "Scoring server response missing 'composite'"}, None

    return float(composite_score), result, duration_sec

def get_rewards(
    self,
    step: int,
    synapse: TalkHeadSynapse,
    responses: List[TalkHeadSynapse],
) -> Tuple[np.ndarray, List[Dict], List[Optional[float]]]:
    """
    Returns an array of rewards for the given query and responses.

    Args:
    - step (int): The current validator step.
    - responses (List[TalkHeadSynapse]): A list of responses from the miner.

    Returns:
    - np.ndarray: An array of rewards for the given query and responses.
    """
    composites: List[float] = []
    detailed_metrics: List[Dict] = []
    latency_ratios: List[Optional[float]] = []

    for video_url, dendrite_process_time in responses:
        if video_url is None or dendrite_process_time is None:
            bt.logging.debug(f"Invalid response: video_url: {video_url} | dendrite_process_time: {dendrite_process_time}")
            composite, metrics, duration_sec = 0.0, {"reason": "Invalid response"}, None
        else:
            composite, metrics, duration_sec = reward(self, step, synapse, video_url)
        composites.append(composite)
        detailed_metrics.append(metrics)
        if duration_sec == None or dendrite_process_time == None:
            latency_ratios.append(0.0)
        else:
            latency_ratios.append(dendrite_process_time / duration_sec)

    return np.array(composites), detailed_metrics, latency_ratios

def compute_latency_scores(latency_ratios: List[Optional[float]], latency_ratio_cap: float = 20.0) -> np.ndarray:
    """
    Map latency ratios (dendrite_process_time / duration_sec) to [0, 1] where:
    - 1.0 corresponds to the minimum observed ratio in the batch
    - 0.0 corresponds to ratio >= latency_ratio_cap
    """
    if len(latency_ratios) == 0:
        return np.array([])

    valid_ratios = [r for r in latency_ratios if r is not None]
    if not valid_ratios:
        return np.zeros(len(latency_ratios))

    min_ratio = min(valid_ratios)
    if min_ratio >= latency_ratio_cap:
        return np.zeros(len(latency_ratios))

    scores: List[float] = []
    for ratio in latency_ratios:
        if ratio is None:
            scores.append(0.0)
            continue
        if ratio <= min_ratio:
            scores.append(1.0)
            continue
        if ratio >= latency_ratio_cap:
            scores.append(0.0)
            continue
        scaled = 1.0 - (ratio - min_ratio) / (latency_ratio_cap - min_ratio)
        scores.append(float(np.clip(scaled, 0.0, 1.0)))

    return np.array(scores)

def apply_blended_rank(rewards: List[float], detailed_metrics: List[Dict], uids: List[int], top_miner_cap: int, decay_rate: float, blend_factor: float, burn_uid: int) -> Tuple[np.ndarray, np.ndarray, List[Dict], bool]:
    """
    Applies a blended ranking model with a quality threshold.
    1. Ranks all miners based on their initial reward scores.
    2. Filters for miners within the top_miner_cap.
    4. Re-ranks the final qualified group and calculates an exponential decay reward.
    5. Blends the rank-based reward with the original reward score.
    6. Miners who do not qualify receive a reward of 0.
    
    Args:
        burn_uid: UID to receive burned emissions (always 59, hardcoded)
    """
    # Convert uids to numpy int32 array for consistent return type
    uids = np.array(uids, dtype=np.int32)
    
    # Get global ranks (0 = best) based on the post-penalty rewards
    rewards = np.array(rewards)

    global_ranks = (-rewards).argsort().argsort()

    # Stage 1: Identify miners within top cap
    within_cap_mask = global_ranks < top_miner_cap
    within_cap_indices = np.where(within_cap_mask)[0]
    final_rewards = np.zeros_like(rewards)
    # Update detailed metrics for logging and analysis (before burn check)
    for i, metrics in enumerate(detailed_metrics):
        metrics['ranking_info'] = {
            'initial_reward': float(rewards[i]), # This is now the post-penalty reward
            'global_rank': int(global_ranks[i]),
            'within_top_cap': bool(within_cap_mask[i]),
            'final_blended_reward': 0.0  # Will be updated if miner qualifies
        }
    if len(within_cap_indices) > 0:
        # Get original rewards for the qualified miners
        within_cap_original_rewards = rewards[within_cap_indices]
        # Re-rank ONLY among the qualified miners
        within_cap_ranks = (-within_cap_original_rewards).argsort().argsort()
        # Calculate exponential decay reward based on rank
        ranked_rewards_component = np.exp(-decay_rate * within_cap_ranks)
        # Blend the rank reward with the original reward
        blended_rewards = (blend_factor * ranked_rewards_component + 
                           (1 - blend_factor) * within_cap_original_rewards)
        # Place the calculated blended rewards into the final rewards array
        final_rewards[within_cap_indices] = blended_rewards
        # Update the final_blended_reward for qualified miners
        for idx, within_cap_idx in enumerate(within_cap_indices):
            detailed_metrics[within_cap_idx]['ranking_info']['final_blended_reward'] = float(blended_rewards[idx])
        bt.logging.info(f"Applied blended ranking: {within_cap_mask.sum()} of {len(rewards)} miners within top cap for rewards.")
        # Return False to indicate 100% burn did not occur (miners qualified)
        return final_rewards, uids, detailed_metrics, False
    else:
        # No miners qualified - burn all emissions
        bt.logging.warning("🔥 BURN EVENT: No miners within top cap after applying top cap")
        bt.logging.warning(f"All emissions will be burned to UID {burn_uid}")
        
        # Extend arrays to include burn UID
        extended_uids = np.append(uids, burn_uid)
        extended_rewards = np.append(final_rewards, 1.0)  # All zeros except burn UID gets 1.0
        
        # Update detailed metrics to include burn UID
        burn_metrics = {
            'uid': burn_uid,
            'is_burn': True,
            'burn_type': '100_percent',  # Indicates 100% burn due to no miners within top cap
            'ranking_info': {
                'initial_reward': 0.0,
                'global_rank': -1,  # Special rank for burn
                'within_top_cap': False,
                'final_blended_reward': 1.0  # Burn gets all rewards
            }
        }
        detailed_metrics.append(burn_metrics)
        
        # Return True to indicate 100% burn occurred (no miners qualified)
        return extended_rewards, extended_uids, detailed_metrics, True
