import os
import dotenv
dotenv.load_dotenv()

TALKHEAD_SERVER_HOST = "https://subnet.talkhead.ai"
TESTNET_TALKHEAD_SERVER_HOST = os.getenv("TESTNET_TALKHEAD_SERVER_HOST", "http://localhost:8001")
SCORING_SERVER_ENDPOINT=os.getenv("SCORING_SERVER_ENDPOINT") or f"{TALKHEAD_SERVER_HOST}/score"
TESTNET_SCORING_SERVER_ENDPOINT=os.getenv("TESTNET_SCORING_SERVER_ENDPOINT", f"{TESTNET_TALKHEAD_SERVER_HOST}/score")
BURN_UID = int(os.getenv("BURN_UID", 0))
BURN_RATIO = float(os.getenv("BURN_RATIO", 1.0))

MINER_SERVER_ENDPOINT=os.getenv("MINER_SERVER_ENDPOINT", "http://localhost:9000/generate")

DENDRITE_TIMEOUT = int(os.getenv("DENDRITE_TIMEOUT", 120))

WANDB_MAX_LOGS = 95_000