# The MIT License (MIT)
# Copyright © 2023 Yuma Rao
# Copyright © 2025 TalkHead AI

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the “Software”), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of
# the Software.

# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

from typing import Optional
import bittensor as bt
from pydantic import Field

# TODO(developer): Rewrite with your protocol definition.

# This is the protocol for the dummy miner and validator.
# It is a simple request-response protocol where the validator sends a request
# to the miner, and the miner responds with a dummy response.

# ---- miner ----
# Example usage:
#   def dummy( synapse: Dummy ) -> Dummy:
#       synapse.dummy_output = synapse.dummy_input + 1
#       return synapse
#   axon = bt.axon().attach( dummy ).serve(netuid=...).start()

# ---- validator ---
# Example usage:
#   dendrite = bt.dendrite()
#   dummy_output = dendrite.query( Dummy( dummy_input = 1 ) )
#   assert dummy_output == 2


class TalkHeadSynapse(bt.Synapse):
    """
    TalkHeadSynapse is a specialized implementation of the `Synapse` class tailored for the TalkHead network.
    It is designed to handle the specific data formats and requirements of the TalkHead network, including
    image, text, and video data.

    Attributes:
    - image: A bytes object representing the image input request sent by the validator.
    - text: A string representing the text input request sent by the validator.
    - video_url: A public URL pointing to the generated video hosted by the miner.
    """

    # Required request input, filled by sending dendrite caller.
    image_base64: str = Field(..., description="The base64 encoded image to use for the talking head.")
    text: str = Field(..., description="The text to generate a talking head for.")
    language: str = Field("en-US", description="The language to use for the talking head.")
    voice_profile: Optional[str] = Field(None, description="The voice profile to use for the talking head.")

    # Optional request output, filled by receiving axon.
    video_url: Optional[str] = Field(None, description="The URL of the video generated by the miner.")

    def deserialize(self) -> str:
        """
        Deserialize the TalkHeadSynapse output. This method retrieves the response from
        the miner in the form of video, deserializes it and returns it
        as the output of the dendrite.query() call.

        Returns:
        - video_url: The URL of the video.

        Example:
        >>> talkhead_synapse = TalkHeadSynapse(image_base64=image_base64, text=text)
        >>> talkhead_synapse.video_url = "https://example.com/video.mp4"
        >>> talkhead_synapse.deserialize()
        "https://example.com/video.mp4"
        """
        return self.video_url
